name: Deploy Lambdas

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "The stage to deploy to (dev or prod)"
        type: choice
        options:
          - dev
          - prod
        required: true

jobs:
  deploy_lambdas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          # Main Functions
          - name: "regroovio-random-tracks"
            path: "./main/api/radio/random-tracks"

          # Bandcamp Workers
          - name: "bandcamp-worker-downloader"
            path: "./bandcamp/workers/downloader"
          - name: "bandcamp-worker-processor"
            path: "./bandcamp/workers/processor"

          # Bandcamp Crons
          - name: "bandcamp-cron-processor"
            path: "./bandcamp/crons/processor"
          - name: "bandcamp-cron-daily"
            path: "./bandcamp/crons/scrapers/daily"
          - name: "bandcamp-cron-custom"
            path: "./bandcamp/crons/scrapers/custom"

          - name: "bandcamp-cron-wishlist"
            path: "./bandcamp/crons/users/wishlist"
          - name: "bandcamp-cron-collection"
            path: "./bandcamp/crons/users/collection"
          - name: "bandcamp-cron-feed"
            path: "./bandcamp/crons/users/feed"

          # Sporify Token Scraper
          - name: "spotify-token"
            path: "./spotify/scrap-token"

          # Sporify Tracks API
          - name: "spotify-get-top"
            path: "./spotify/api/tracks/get-top"
          - name: "spotify-get-likes"
            path: "./spotify/api/tracks/get-likes"
          - name: "spotify-add-tracks"
            path: "./spotify/api/tracks/add-tracks"
          - name: "spotify-get-playlist"
            path: "./spotify/api/tracks/get-playlist"
          - name: "spotify-get-audio-features"
            path: "./spotify/api/tracks/get-audio-features"
          - name: "spotify-get-audio-analysis"
            path: "./spotify/api/tracks/get-audio-analysis"

          # Sporify Auth API
          - name: "spotify-login"
            path: "./spotify/api/auth/login"
          - name: "spotify-callback"
            path: "./spotify/api/auth/callback"
          - name: "spotify-refresh"
            path: "./spotify/api/auth/refresh"
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          cd ${{ matrix.function.path }}
          npm ci --production

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ${{ matrix.function.path }}/node_modules
          key: ${{ matrix.function.path }}-${{ inputs.stage }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.function.path }}-${{ inputs.stage }}-

      - name: Package Lambda function
        run: |
          cd ${{ matrix.function.path }}
          zip -r ${{ matrix.function.name }}-${{ inputs.stage }}.zip .
          aws s3 cp ${{ matrix.function.name }}-${{ inputs.stage }}.zip s3://lambdas-regroovio-${{ inputs.stage }}
          rm ${{ matrix.function.name }}-${{ inputs.stage }}.zip

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.function.name }}-${{ inputs.stage }} \
            --s3-bucket lambdas-regroovio-${{ inputs.stage }} \
            --s3-key ${{ matrix.function.name }}-${{ inputs.stage }}.zip

      - name: Wait for Lambda update
        run: |
          aws lambda wait function-updated --function-name ${{ matrix.function.name }}-${{ inputs.stage }}

      - name: Update Lambda function configuration
        run: |
          aws lambda update-function-configuration \
          --function-name ${{ matrix.function.name }}-${{ inputs.stage }} \
          --region us-east-1 \
          --environment "Variables={
          AUTH_LAMBDA=\"https://${{ inputs.stage }}.auth.regroovio.com\",
          STAGE=\"${{ inputs.stage }}\",
          ${{ secrets.LAMBDAS_ENV }}
          }"
