name: Dispatch Deploy (Lambdas);
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dispatch Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run deploy-lambdas.yml --ref main -f stage=prod -f functions=all
