name: Dispatch Deploy (Lambdas);
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dispatch Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deploy-lambdas
          client-payload: '{"stage": "prod", "functions": "${{ steps.filter_functions.outputs.filtered_functions }}"}'