name: Dispatch Deploy (Lambdas);
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Deploy
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run workflow --ref branch-main -f stage=prod functions=all