name: Dispatch Deploy (Lambdas);
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dispatch Deploy
        run: gh workflow run workflow --ref branch-main -f stage=prod functions=all